### ISSUE TITLE
请问一下这里的 EventEmitter 是来自哪里的？

### ISSUE THREAD

**Issue by fishenal** [Geocld/vue-note-firebase-app#1]
求教~ events是哪里的？

**Comment by Geocld** [comment]
events是node.js内置的模块，所以你在package.json里看不到这个包，EventEmitter则是从events里提取事件触发方法。

**Comment by fishenal** [comment]
头一次见到拿node里的模块来用的， 那这部分模块代码也会被最终build到目标目录是吧

**Comment by Geocld** [comment]
对，这部分模块代码最后都会集成在build的文件中
